-- ============================================================
-- Personal Website — Supabase Schema Reference
-- Last updated: 2 Juli 2026
-- ============================================================
-- Cara eksekusi: Jalankan file ini di SQL Editor Supabase
-- Bucket storage 'portfolio' harus dibuat manual di dashboard Supabase Storage
-- ============================================================

-- ============================================================
-- 1. Table: Personal Info
-- ============================================================
create table public.personal (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  bio text,
  location text,
  email text,
  github_url text,
  linkedin_url text,
  instagram_url text,
  resume_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table: Skills
create table public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'Frontend', 'Backend & AI', 'Tools & Others'
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2a. Table: Education
-- CATATAN: Tabel ini sudah dipakai oleh kode (src/lib/queries/education.ts dan /admin/education)
-- tetapi TIDAK ADA di file schema ini sebelumnya — ditambahkan agar schema referensi sinkron dengan DB asli.
create table public.education (
  id bigint generated by default as identity primary key,
  institution text not null,
  degree text not null,
  field text not null,
  start_year text,
  end_year text,
  description text,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Table: Experiences
create table public.experiences (
  id bigint generated by default as identity primary key,
  title text not null,
  organization text not null,
  type text not null, -- 'organization' or 'committee'
  start_date date,
  end_date date, -- NULL indicates 'Sekarang' / Present
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Table: Experience Images (One-to-many relationship with experiences)
-- Storing image configuration/metadata
create table public.experience_images (
  id bigint generated by default as identity primary key,
  experience_id bigint references public.experiences(id) on delete cascade not null,
  src text not null, -- path in storage or full url
  position text default 'center center', -- for object-position
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Table: Projects
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tags text[], -- Array of strings
  demo_url text,
  github_url text,
  featured boolean default false,
  status text check (status in ('ongoing', 'completed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Table: Project Images (One-to-many relationship with projects)
create table public.project_images (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade not null,
  src text not null,
  position text default 'center center',
  zoom numeric default 1,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- ============================================================
-- Storage Buckets Setup
-- ============================================================
-- Buat bucket bernama 'portfolio' di Supabase Storage dashboard.
-- Set policies: public read, authenticated insert/update/delete.

-- ============================================================
-- Row Level Security (RLS) — Aktifkan di setiap tabel
-- ============================================================

alter table public.personal enable row level security;
alter table public.skills enable row level security;
alter table public.education enable row level security;
alter table public.experiences enable row level security;
alter table public.experience_images enable row level security;
alter table public.projects enable row level security;
alter table public.project_images enable row level security;

-- Policy: Public dapat membaca semua data
create policy "Public read access" on public.personal for select using (true);
create policy "Public read access" on public.skills for select using (true);
create policy "Public read access" on public.education for select using (true);
create policy "Public read access" on public.experiences for select using (true);
create policy "Public read access" on public.experience_images for select using (true);
create policy "Public read access" on public.projects for select using (true);
create policy "Public read access" on public.project_images for select using (true);

-- ⚠️ EMAIL ADMIN SUDAH DIISI OTOMATIS: kevinlubis2909@gmail.com
-- (diambil dari data publik tabel personal). SEBELUM menjalankan file ini,
-- PASTIKAN email tersebut SAMA dengan email yang dipakai untuk login di
-- /admin/login (Supabase Auth). Jika berbeda, ganti semua 'kevinlubis2909@gmail.com'
-- pada policy di bawah dengan email login yang benar.
--
-- MENGAPA DIPERKETAT:
-- Policy lama ('Authenticated write access') memberi akses write ke SEMUA user
-- terautentikasi (auth.role() = 'authenticated'). Artinya: siapa pun yang berhasil
-- membuat akun di project Supabase ini bisa mengubah/menghapus SEMUA data portfolio
-- dan gambar. Policy baru membatasi write hanya untuk pemilik (email admin).
--
-- Ingin lebih dari satu admin? Ganti dengan custom claim, misalnya:
--   using ( auth.jwt() -> 'app_metadata' ->> 'role' = 'admin' )
--
-- Policy: Hanya admin (pemilik) yang dapat write
-- (pakai with check agar INSERT juga dicek, dan drop policy if exists agar idempotent)
drop policy if exists "Authenticated write access" on public.personal;
create policy "Admin write access" on public.personal
  for all
  using (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com')
  with check (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com');
drop policy if exists "Authenticated write access" on public.skills;
create policy "Admin write access" on public.skills
  for all
  using (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com')
  with check (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com');
drop policy if exists "Authenticated write access" on public.education;
create policy "Admin write access" on public.education
  for all
  using (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com')
  with check (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com');
drop policy if exists "Authenticated write access" on public.experiences;
create policy "Admin write access" on public.experiences
  for all
  using (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com')
  with check (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com');
drop policy if exists "Authenticated write access" on public.experience_images;
create policy "Admin write access" on public.experience_images
  for all
  using (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com')
  with check (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com');
drop policy if exists "Authenticated write access" on public.projects;
create policy "Admin write access" on public.projects
  for all
  using (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com')
  with check (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com');
drop policy if exists "Authenticated write access" on public.project_images;
create policy "Admin write access" on public.project_images
  for all
  using (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com')
  with check (auth.jwt() ->> 'email' = 'kevinlubis2909@gmail.com');

-- Pastikan tabel personal hanya berisi SATU baris (data profil tunggal)
create unique index if not exists personal_single_row on public.personal ((true));

-- ============================================================
-- Indexes (untuk performa query)
-- ============================================================

create index if not exists idx_skills_category on public.skills(category);
create index if not exists idx_skills_sort_order on public.skills(sort_order);
-- Composite index untuk query skills: filter category + order by sort_order
create index if not exists idx_skills_category_sort on public.skills(category, sort_order);
create index if not exists idx_experiences_start_date on public.experiences(start_date desc);
create index if not exists idx_experience_images_experience_id on public.experience_images(experience_id);
create index if not exists idx_projects_status on public.projects(status);
create index if not exists idx_projects_featured on public.projects(featured);
-- Composite index untuk query projects: order by featured desc, created_at desc
create index if not exists idx_projects_featured_created on public.projects(featured desc, created_at desc);
create index if not exists idx_project_images_project_id on public.project_images(project_id);
-- Index untuk tabel education
create index if not exists idx_education_sort_order on public.education(sort_order);
