-- Enable Row Level Security (RLS) is generally good practice, 
-- but for simplicity in this personal admin panel, we might start open or just authenticated.
-- modifying to include basic structure.

-- 1. Table: Personal Info
create table public.personal (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  bio text,
  location text,
  email text,
  github_url text,
  linkedin_url text,
  instagram_url text,
  resume_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table: Skills
create table public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'Frontend', 'Backend & AI', 'Tools & Others'
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Table: Experiences
create table public.experiences (
  id bigint generated by default as identity primary key,
  title text not null,
  organization text not null,
  type text not null, -- 'organization' or 'committee'
  start_date date,
  end_date date, -- NULL indicates 'Sekarang' / Present
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Table: Experience Images (One-to-many relationship with experiences)
-- Storing image configuration/metadata
create table public.experience_images (
  id bigint generated by default as identity primary key,
  experience_id bigint references public.experiences(id) on delete cascade not null,
  src text not null, -- path in storage or full url
  position text default 'center center', -- for object-position
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Table: Projects
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_src text,
  image_position text default 'center center',
  tags text[], -- Array of strings
  demo_url text,
  github_url text,
  featured boolean default false,
  status text check (status in ('ongoing', 'completed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed some initial data if needed (Optional)
-- You can run this after creating tables to not start empty.

-- Storage Buckets Setup
-- You will need to create a bucket named 'portfolio' in the Supabase Storage dashboard.
-- And set policies to allow public read, and authenticated insert/update/delete.
