-- ============================================================
-- Incremental hardening — jalankan di Supabase SQL Editor
-- Project: personal-website (existing database)
-- ============================================================
-- File ini AMAN untuk database yang sudah ada (pakai IF NOT EXISTS
-- dan drop policy if exists). Tidak perlu menjalankan supabase_schema.sql
-- atau supabase_storage_setup.sql penuh di project yang sudah live.
--
-- ⚠️ Sebelum menjalankan: pastikan 'YOUR_ADMIN_EMAIL@example.com' di bawah
--    SAMA dengan email yang dipakai login di /admin/login (Supabase Auth).
--    Jika beda, ganti semua baris email tersebut dulu.
-- ============================================================

-- ── 1) Tabel education (tidak ada di DB live, tapi dipakai kode) ──
create table if not exists public.education (
  id bigint generated by default as identity primary key,
  institution text not null,
  degree text not null,
  field text not null,
  start_year text,
  end_year text,
  description text,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.education enable row level security;

create policy "Public read access" on public.education for select using (true);

drop policy if exists "Authenticated write access" on public.education;
create policy "Admin write access" on public.education
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com');

create index if not exists idx_education_sort_order on public.education(sort_order);

-- ── 2) Perketat policy write di tabel yang SUDAH ada ──
-- Sebelumnya: siapa pun yang terautentikasi bisa write (auth.role() = 'authenticated')
-- Sekarang: hanya admin (email di bawah) yang bisa write

drop policy if exists "Authenticated write access" on public.personal;
create policy "Admin write access" on public.personal
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com');

drop policy if exists "Authenticated write access" on public.skills;
create policy "Admin write access" on public.skills
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com');

drop policy if exists "Authenticated write access" on public.experiences;
create policy "Admin write access" on public.experiences
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com');

drop policy if exists "Authenticated write access" on public.experience_images;
create policy "Admin write access" on public.experience_images
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com');

drop policy if exists "Authenticated write access" on public.projects;
create policy "Admin write access" on public.projects
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com');

drop policy if exists "Authenticated write access" on public.project_images;
create policy "Admin write access" on public.project_images
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com');

-- ── 3) Pengaman data + index tambahan ──
-- Cegah duplikasi baris di tabel personal (harusnya hanya 1 baris profil)
create unique index if not exists personal_single_row on public.personal ((true));

-- Composite index agar query sorting skills/projects memakai index
create index if not exists idx_skills_category_sort on public.skills(category, sort_order);
create index if not exists idx_projects_featured_created on public.projects(featured desc, created_at desc);

-- ── 4) Storage bucket 'portfolio': hanya admin yang bisa upload/update/delete ──
drop policy if exists "Authenticated Upload" on storage.objects;
create policy "Admin Upload" on storage.objects
  for insert to authenticated
  with check ( bucket_id = 'portfolio' and auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com' );

drop policy if exists "Authenticated Update" on storage.objects;
create policy "Admin Update" on storage.objects
  for update to authenticated
  using ( bucket_id = 'portfolio' and auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com' );

drop policy if exists "Authenticated Delete" on storage.objects;
create policy "Admin Delete" on storage.objects
  for delete to authenticated
  using ( bucket_id = 'portfolio' and auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@example.com' );

-- ============================================================
-- Selesai. Verifikasi:
--   1. Coba akses /admin/login dengan akun admin → CRUD harus tetap jalan
--   2. Coba dengan akun NON-admin (jika ada) → semua write harus ditolak 403
-- ============================================================
