-- ============================================================
-- Personal Website — Supabase Schema Reference
-- Last updated: 2 Juli 2026
-- ============================================================
-- Cara eksekusi: Jalankan file ini di SQL Editor Supabase
-- Bucket storage 'portfolio' harus dibuat manual di dashboard Supabase Storage
-- ============================================================

-- ============================================================
-- 1. Table: Personal Info
-- ============================================================
create table public.personal (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  bio text,
  location text,
  email text,
  github_url text,
  linkedin_url text,
  instagram_url text,
  resume_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table: Skills
create table public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'Frontend', 'Backend & AI', 'Tools & Others'
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Table: Experiences
create table public.experiences (
  id bigint generated by default as identity primary key,
  title text not null,
  organization text not null,
  type text not null, -- 'organization' or 'committee'
  start_date date,
  end_date date, -- NULL indicates 'Sekarang' / Present
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Table: Experience Images (One-to-many relationship with experiences)
-- Storing image configuration/metadata
create table public.experience_images (
  id bigint generated by default as identity primary key,
  experience_id bigint references public.experiences(id) on delete cascade not null,
  src text not null, -- path in storage or full url
  position text default 'center center', -- for object-position
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Table: Projects
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tags text[], -- Array of strings
  demo_url text,
  github_url text,
  featured boolean default false,
  status text check (status in ('ongoing', 'completed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Table: Project Images (One-to-many relationship with projects)
create table public.project_images (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade not null,
  src text not null,
  position text default 'center center',
  zoom numeric default 1,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- ============================================================
-- Storage Buckets Setup
-- ============================================================
-- Buat bucket bernama 'portfolio' di Supabase Storage dashboard.
-- Set policies: public read, authenticated insert/update/delete.

-- ============================================================
-- Row Level Security (RLS) — Aktifkan di setiap tabel
-- ============================================================

alter table public.personal enable row level security;
alter table public.skills enable row level security;
alter table public.experiences enable row level security;
alter table public.experience_images enable row level security;
alter table public.projects enable row level security;
alter table public.project_images enable row level security;

-- Policy: Public dapat membaca semua data
create policy "Public read access" on public.personal for select using (true);
create policy "Public read access" on public.skills for select using (true);
create policy "Public read access" on public.experiences for select using (true);
create policy "Public read access" on public.experience_images for select using (true);
create policy "Public read access" on public.projects for select using (true);
create policy "Public read access" on public.project_images for select using (true);

-- Policy: Hanya user yang terautentikasi (admin) yang dapat write
create policy "Authenticated write access" on public.personal for all using (auth.role() = 'authenticated');
create policy "Authenticated write access" on public.skills for all using (auth.role() = 'authenticated');
create policy "Authenticated write access" on public.experiences for all using (auth.role() = 'authenticated');
create policy "Authenticated write access" on public.experience_images for all using (auth.role() = 'authenticated');
create policy "Authenticated write access" on public.projects for all using (auth.role() = 'authenticated');
create policy "Authenticated write access" on public.project_images for all using (auth.role() = 'authenticated');

-- ============================================================
-- Indexes (untuk performa query)
-- ============================================================

create index if not exists idx_skills_category on public.skills(category);
create index if not exists idx_skills_sort_order on public.skills(sort_order);
create index if not exists idx_experiences_start_date on public.experiences(start_date desc);
create index if not exists idx_experience_images_experience_id on public.experience_images(experience_id);
create index if not exists idx_projects_status on public.projects(status);
create index if not exists idx_projects_featured on public.projects(featured);
create index if not exists idx_project_images_project_id on public.project_images(project_id);
